services:
  - type: web
    name: api-desa-cigedug
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: "https://uujiuvjibnvxuxmxajxn.supabase.co"
      - key: SUPABASE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
